document.writeln("<table width=\"950\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
document.writeln("  <tr>");
document.writeln("    <td><table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#e8fafa\" class=\"foot_topborder\">");
document.writeln("        <tr> ");
document.writeln("          <td width=\"47%\" valign=\"top\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"first1_top\">");
document.writeln("              <tr> ");
document.writeln("                <td><h1 class=\"font1\"><a href=\"http://www.wenweipo.com/mainland.phtml\" target=\"_blank\"><font color=\"#1c8a85\">文匯報屬下辦站</font></a></h1></td>");
document.writeln("              </tr>");
document.writeln("              <tr> ");
document.writeln("                <td align=\"right\" valign=\"top\"><table width=\"99%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"first1_link\">");
document.writeln("                    <tr> ");
document.writeln("                      <td height=\"16\" align=\"center\"><a href=\"http://bj.wenweipo.com\" target=\"_blank\">北京</a></td>");
document.writeln("                      <td align=\"center\"><a href=\"http://www.wenweipo.com/mainland.phtml#sh\" target=\"_blank\">上海</a></td>");
document.writeln("                      <td align=\"center\"><a href=\"http://gd.wenweipo.com/\" target=\"_blank\">廣州</a></td>");
document.writeln("                      <td align=\"center\"><a href=\"http://www.wenweipo.com/mainland.phtml#sz\" target=\"_blank\">深圳</a></td>");
document.writeln("                      <td align=\"center\"><a href=\"http://www.wenweipo.com/mainland.phtml#zj\" target=\"_blank\">珠海</a></td>");
document.writeln("                      <td align=\"center\"><a href=\"http://www.wenweipo.com/mainland.phtml#cq\" target=\"_blank\">重慶</a></td>");
document.writeln("                      <td align=\"center\"><a href=\"http://www.wenweipo.com/mainland.phtml#tj\" target=\"_blank\">天津</a></td>");
document.writeln("                      <td align=\"center\"><a href=\"http://www.wenweipo.com/mainland.phtml#ln\" target=\"_blank\">遼寧</a></td>");
document.writeln("                      <td align=\"center\"><a href=\"http://www.wenweipo.com/mainland.phtml#jl\" target=\"_blank\">吉林</a></td>");
document.writeln("                      <td><a href=\"http://www.wenweipo.com/mainland.phtml#lj\" target=\"_blank\">黑龍江</a></td>");
document.writeln("                    </tr>");
document.writeln("                    <tr> ");
document.writeln("                      <td height=\"16\" align=\"center\"><a href=\"http://www.wenweipo.com/mainland.phtml#sd\" target=\"_blank\">山東</a></td>");
document.writeln("                      <td align=\"center\"><a href=\"http://www.wenweipo.com/mainland.phtml#sx\" target=\"_blank\">山西</a><a href=\"http://www.sd.wenweipo.com/\" target=\"_blank\"></a></td>");
document.writeln("                      <td align=\"center\"><a href=\"http://www.wenweipo.com/mainland.phtml#hb\" target=\"_blank\">河北</a></td>");
document.writeln("                      <td align=\"center\"><a href=\"http://hn.wenweipo.com\" target=\"_blank\">河南</a></td>");
document.writeln("                      <td align=\"center\"><a href=\"http://www.wenweipo.com/mainland.phtml#nj\" target=\"_blank\">江蘇</a><a href=\"#\" target=\"_blank\"></a></td>");
document.writeln("                      <td align=\"center\"><a href=\"http://www.wenweipo.com/mainland.phtml#wh\" target=\"_blank\">武漢</a></td>");
document.writeln("                      <td align=\"center\"><a href=\"http://www.wenweipo.com/mainland.phtml#af\" target=\"_blank\">安徽</a></td>");
document.writeln("                      <td align=\"center\"><a href=\"http://www.wenweipo.com/mainland.phtml#zj\" target=\"_blank\">浙江</a></td>");
document.writeln("                      <td align=\"center\"><a href=\"http://www.wenweipo.com/mainland.phtml#jx\" target=\"_blank\">江西</a></td>");
document.writeln("                      <td><a href=\"http://www.wenweipo.com/mainland.phtml#fj\" target=\"_blank\">福建</a></td>");
document.writeln("                    </tr>");
document.writeln("                    <tr> ");
document.writeln("                      <td height=\"16\" align=\"center\"><a href=\"http://www.wenweipo.com/mainland.phtml#un\" target=\"_blank\">湖南</a></td>");
document.writeln("                      <td align=\"center\"><a href=\"http://www.wenweipo.com/mainland.phtml#ssx\" target=\"_blank\">陝西</a></td>");
document.writeln("                      <td align=\"center\"><a href=\"http://www.wenweipo.com/mainland.phtml#nx\" target=\"_blank\">寧夏</a></td>");
document.writeln("                      <td align=\"center\"><a href=\"http://www.wenweipo.com/mainland.phtml#xb\" target=\"_blank\">甘肅</a></td>");
document.writeln("                      <td align=\"center\"><a href=\"http://www.wenweipo.com/mainland.phtml#xj\" target=\"_blank\">新疆</a></td>");
document.writeln("                      <td align=\"center\"><a href=\"http://yn.wenweipo.com/\" target=\"_blank\">雲南</a></td>");
document.writeln("                      <td align=\"center\"><a href=\"http://sc.wenweipo.com/\" target=\"_blank\">四川</a></td>");
document.writeln("                      <td align=\"center\"><a href=\"http://www.wenweipo.com/mainland.phtml#gu\" target=\"_blank\">貴州</a></td>");
document.writeln("                      <td align=\"center\"><a href=\"http://gx.wenweipo.com/\" target=\"_blank\">廣西</a></td>");
document.writeln("                      <td><a href=\"http://www.wenweipo.com/mainland.phtml#an\" target=\"_blank\">海南</a></td>");
document.writeln("                    </tr>");
document.writeln("                  </table>");
document.writeln("                  <table width=\"99%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"first1_link\">");
document.writeln("                    <tr>");
document.writeln("                      <td align=\"center\" width=\"12%\"><a href=\"http://www.wenweipo.com/mainland.phtml#nmg\" target=\"_blank\">內蒙古</a></td>");
document.writeln("                      <td align=\"center\" width=\"10%\"><a href=\"http://www.wenweipo.com/mainland.phtml#qh\" target=\"_blank\">青海</a></td>");
document.writeln("                      <td align=\"center\" width=\"10%\"><a href=\"http://www.wenweipo.com/mainland.phtml#mac\" target=\"_blank\">澳門</a></td>");
document.writeln("                      <td width=\"25%\" height=\"16\" align=\"center\"><a href=\"http://sp.wenweipo.com/address-md/\" target=\"_blank\">中國內地財經部</a></td>");
document.writeln("                      <td align=\"center\" width=\"25%\"><a href=\"http://sp.wenweipo.com/address-md/\" target=\"_blank\">上市公司工作部</a></td>");
document.writeln("                      <td>&nbsp;</td>");
document.writeln("                    </tr>");
document.writeln("                    </tr>");
document.writeln("                  </table></td>");
document.writeln("              </tr>");
document.writeln("            </table></td>");
document.writeln("          <td width=\"28%\" valign=\"top\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"first1_top\">");
document.writeln("              <tr> ");
document.writeln("                <td><h1 class=\"font1\"><a href=\"#\"><font color=\"#1c8a85\">文匯報屬下公司</font></a></h1></td>");
document.writeln("              </tr>");
document.writeln("              <tr> ");
document.writeln("                <td height=\"13\" align=\"right\"><table width=\"97%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"first1_link\">");
document.writeln("                    <tr> ");
document.writeln("                      <td height=\"16\"><A href=\"http://sp.wenweipo.com/wwpprc/\" target=_blank>文匯國際公關公司</A></td>");
document.writeln("                      <td height=\"16\"><a href=\"http://www.wenweipublish.com/\" target=\"_blank\">文匯出版社</a></td>");
document.writeln("                    </tr>");
document.writeln("                    <tr> ");
document.writeln("                      <td height=\"16\"><a href=\"http://sp.wenweipo.com/wahwei-adv/wahwei-adv.html\" target=\"_blank\">華匯廣告公司</a></td>");
document.writeln("                      <td height=\"16\"><a href=\"http://sp.wenweipo.com/athens/athens.html\" target=\"_blank\">雅典美術印製公司</a></td>");
document.writeln("                    </tr>");
document.writeln("                  </table></td>");
document.writeln("              </tr>");
document.writeln("            </table></td>");
document.writeln("          <td valign=\"top\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"first1_top\">");
document.writeln("              <tr> ");
document.writeln("                <td><h1 class=\"font1\"><a href=\"http://pdf.wenweipo.com/os/\" target=\"_blank\"><font color=\"#1c8a85\">文匯海外版</font></a></h1></td>");
document.writeln("              </tr>");
document.writeln("              <tr> ");
document.writeln("                <td align=\"right\"><table width=\"98%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" class=\"first1_link\">");
document.writeln("                    <tr> ");
document.writeln("                      <td height=\"16\"><a href=\"http://pdf.wenweipo.com/os/overseas-1.php\" target=\"_blank\">美洲版</a></td>");
document.writeln("                      <td height=\"16\"><a href=\"http://pdf.wenweipo.com/os/overseas-2.php\" target=\"_blank\">東南亞版</a></td>");
document.writeln("                      <td height=\"16\"><a href=\"http://pdf.wenweipo.com/os/overseas-3.php\" target=\"_blank\">泰國版</a></td>");
document.writeln("                    </tr>");
document.writeln("                    <tr> ");
document.writeln("                      <td height=\"16\"><a href=\"http://pdf.wenweipo.com/os/overseas-4.php\" target=\"_blank\">加拿大版</a></td>");
document.writeln("                      <td height=\"16\"><a href=\"http://pdf.wenweipo.com/os/overseas-5.php\" target=\"_blank\">菲律賓版</a></td>");
document.writeln("                      <td height=\"16\"><a href=\"http://pdf.wenweipo.com/os/overseas-6.php\" target=\"_blank\">西馬版</a></td>");
document.writeln("                    </tr>");
document.writeln("                    <tr> ");
document.writeln("                      <td height=\"16\"><a href=\"http://pdf.wenweipo.com/os/overseas-7.php\" target=\"_blank\">東馬沙勞越版</a></td>");
document.writeln("                      <td height=\"16\"><a href=\"http://pdf.wenweipo.com/os/overseas-8.php\" target=\"_blank\">東馬沙巴版</a></td>");
document.writeln("                      <td height=\"16\"><a href=\"http://pdf.wenweipo.com/os/overseas-9.php\" target=\"_blank\">北馬版</a></td>");
document.writeln("                    </tr>");
document.writeln("                    <tr><td colspan=\"3\"><table width=\"100%\" class=\"first1_link\"><tr> ");
document.writeln("                      <td height=\"16\"><a href=\"http://pdf.wenweipo.com/os/overseas-10.php\" target=\"_blank\">英國版</a></td>");
document.writeln("                      <td height=\"16\"><a href=\"http://pdf.wenweipo.com/os/overseas-11.php\" target=\"_blank\">歐洲版</a></td>");
document.writeln("                      <td height=\"16\"><a href=\"http://pdf.wenweipo.com/os/overseas-12.php\" target=\"_blank\">台灣專版</a></td>");
document.writeln("                      <td height=\"16\"><a href=\"http://pdf.wenweipo.com/os/overseas-13.php\" target=\"_blank\">韓國專版</a></td>");
document.writeln("                    </tr></table></td></tr>");
document.writeln("                  </table></td>");
document.writeln("              </tr>");
document.writeln("            </table></td>");
document.writeln("        </tr>");
document.writeln("      </table></td>");
document.writeln("  </tr>");
document.writeln("  <tr> ");
document.writeln("    <td align=\"right\"><table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" height=\"28\">");
document.writeln("        <tr> ");
document.writeln("          <td width=\"529\" align=\"left\">&nbsp;<font class=\"font1\" color=\"#1c8a85\">香港文匯報新媒體中心　版權所有 <span style='font-family:Arial'>&copy;</span>");
var date = new Date();
var year = date.getFullYear();
document.writeln("1997-"+year+" WENWEIPO.COM LIMITED.</font></td>");
document.writeln("           <td width=\"270\" align=\"right\"><font class=\"font1\" color=\"#1c8a85\">|</font> <a href=\"http://www.wenweipo.com/advert-newspaper-hkd.phtml\"><font class=\"font1\" color=\"#1c8a85\">廣告</font></a> ");
document.writeln("            <font class=\"font1\" color=\"#1c8a85\">|</font> <a href=\"http://www.wenweipo.com/aboutus.phtml\"><font class=\"font1\" color=\"#1c8a85\">關於我們</font></a> <font class=\"font1\" color=\"#1c8a85\">|</font> <a href=\"http://www.wenweipo.com/sitemap.php\" target=\"_blank\"><font class=\"font1\" color=\"#1c8a85\">網站地圖</font></a> </td>");
document.writeln("        </tr>");
document.writeln("      </table></td>");
document.writeln("  </tr>");
document.writeln("</table>");
document.writeln('<script type="text/javascript" src="http://c.wrating.com/a1.js"></script>');
document.writeln('<script type="text/javascript" src="http://image.wenweipo.com/2009new/js/getacc.js"></script>');